import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CityService {
  cities = [
    'Abidjan (Ivory Coast)',
    'Accra (Ghana)',
    'Ahmadabad (India)',
    'Alexandria (Egypt)',
    'Ankara (Turkey)',
    'Atlanta (United States)',
    'Baghdad (Iraq)',
    'Bandung (Indonesia)',
    'Bangalore (India)',
    'Bangkok (Thailand)',
    'Barcelona (Spain)',
    'Beijing (China)',
    'Belo Horizonte (Brazil)',
    'Berlin (Germany)',
    'Bogota (Colombia)',
    'Boston (United States)',
    'Buenos Aires (Argentina)',
    'Cairo (Egypt)',
    'Chengdu (China)',
    'Chennai (India)',
    'Chicago (United States)',
    'Chongqing (China)',
    'Dalian (China)',
    'Dallas-Fort Worth (United States)',
    'Dar es Salaam (Tanzania)',
    'Delhi (India)',
    'Dhaka (Bangladesh)',
    'Dongguan (China)',
    'Essen-Dusseldorf (Germany)',
    'Fuzhou (China)',
    'Guadalajara (Mexico)',
    'Guangzhou-Foshan (China)',
    'Hangzhou (China)',
    'Harbin (China)',
    'Ho Chi Minh City (Vietnam)',
    'Hong Kong (China: Hong Kong SAR)',
    'Houston (United States)',
    'Hyderabad (India)',
    'Istanbul (Turkey)',
    'Jakarta (Indonesia)',
    'Johannesburg-East Rand (South Africa)',
    'Kabul (Afghanistan)',
    'Karachi (Pakistan)',
    'Khartoum (Sudan)',
    'Kinshasa (Congo (Dem. Rep.))',
    'Kolkata (India)',
    'Kuala Lumpur (Malaysia)',
    'Kuwait (Kuwait)',
    'Lagos (Nigeria)',
    'Lahore (Pakistan)',
    'Lima (Peru)',
    'London (United Kingdom)',
    'Los Angeles, CA (United States)',
    'Luanda (Angola)',
    'Madrid (Spain)',
    'Manila (Philippines)',
    'Medan (Indonesia)',
    'Mexico City (Mexico)',
    'Miami (United States)',
    'Milan (Italy)',
    'Monterrey (Mexico)',
    'Moscow (Russia)',
    'Mumbai (India)',
    'Nagoya (Japan)',
    'Nairobi (Kenya)',
    'Nanjing (China)',
    'New York (United States)',
    'Osaka-Kobe-Kyoto (Japan)',
    'Paris (France)',
    'Philadelphia (United States)',
    'Phoenix (United States)',
    'Pune (India)',
    'Qingdao (China)',
    'Quanzhou (China)',
    'Rio de Janeiro (Brazil)',
    'Riyadh (Saudi Arabia)',
    'San Francisco (United States)',
    'Santiago (Chile)',
    'Sao Paulo (Brazil)',
    'Seoul-Incheon (South Korea)',
    'Shanghai (China)',
    'Shenyang (China)',
    'Shenzhen (China)',
    'Singapore (Singapore)',
    'St. Petersburg (Russia)',
    'Surabaya (Indonesia)',
    'Surat (India)',
    'Suzhou (China)',
    'Sydney (Australia)',
    'Taipei (China: Taiwan)',
    'Tehran (Iran)',
    'Tianjin (China)',
    'Tokyo-Yokohama (Japan)',
    'Toronto (Canada)',
    'Washington (United States)',
    'Wuhan (China)',
    'Xiamen (China)',
    'Xi\'an (China)',
    'Yangon (Myanmar)',
    'Zhengzhou (China)',
  ];

  list() {
    return this.cities;
  }
}
